menu:
- {name: 'publications', url: '/publications'}
- {name: 'resume', url: '/cv'}
- {name: 'projects', url: "#ProjectSection"}

social:
- {icon: 'github', link: 'https://github.com/nithinbharathi'}
- {icon: 'twitter', link: 'https://twitter.com/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/nithin-bharathi-798754167/'}
